name: "Format Issue ID"
description: "Replaces placeholder or appends formatted ID to GitHub issue titles"

inputs:
  prefix:
    description: "Prefix for the identifier (e.g., TZF)"
    required: true
  placeholder:
    description: "Optional placeholder to replace (e.g., X)"
    required: false
  dry_run:
    description: "If true, logs the new title but doesn't update"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        chmod +x "${{ github.action_path }}/format.sh"
        "${{ github.action_path }}/format.sh" \
          "${{ github.event.issue.number }}" \
          "${{ github.event.issue.title }}" \
          "${{ inputs.prefix }}" \
          "${{ inputs.placeholder }}" \
          "${{ inputs.dry_run }}"
